Update path with anaconda in dockerfile - can't build w/o it
The anaconda path needs to be explicitely added to the path when
building in docker:

 ---> Running in 4dd60948ffa2
+ pip install six
/bin/sh: 1: pip: not found
ERROR: Service 'dtale_2_7' failed to build: The command '/bin/sh -c set -eux   ; pip install six   ; pip install lxml   ; pip install isort   ; pip install -r docs/source/requirements.txt   ; python setup.py develop   ; python setup.py build_sphinx   ; isort --recursive -c -vb setup.py dtale tests   ; export TZ=America/New_York   ; python setup.py test   ; python setup.py bdist_egg' returned a non-zero code: 127